# config.py
TELEGRAM_TOKEN = 'token'
QBITTORRENT_URL = 'http://localhost:8080'
QBITTORRENT_USERNAME = 'user'
QBITTORRENT_PASSWORD = 'pass'
NOTIFY_CHAT_ID = 1
CHECK_COMPLETED_INTERVAL = 60
NOTIFIED_FILE = "notified.txt"
